### ISSUE TITLE
SL/LMatrix?

### ISSUE THREAD

**Issue by rafaqz** [JuliaDiffEq/LabelledArrays.jl#11]
What are your thoughts on extending this to include 2 dimensional arrays? 

It would be great to have symbolic indexing with no overheads in two dimensions as well, its something I tend to use a lot but I had to use constants instead of symbols for performance reasons in julia 0.6. It would probably be better to add that functionality here than write another package.

**Comment by ChrisRackauckas** [comment]
It can be done using the same techniques.

**Comment by rafaqz** [comment]
Ok I'll put together a PR

**Comment by rafaqz** [comment]
I was imagining accessing the matrix like:

```julia
array[:A, :b]
```
but this is also fine:

```julia
array.a.b
```
Does that fit with using a linear index? I'm not sure I understand what you mean.

**Comment by ChrisRackauckas** [comment]
oh that's different, but possible to implement.

**Comment by ChrisRackauckas** [comment]
I think we can just make it LArray which uses the linear indexing from the array type. That shouldn't be so hard to setup I would think?

**Comment by Deduction42** [comment]
I don't know what the status is on this but as an example, it would be nice to have linear indexing on more than one dimension and have concatenation work numerically. For example

x = LArray{Float64,1,(:a, :b, :c)}([1,2,3])
X = [x*0 x*1 x*2 x*3]

and have it so that the first dimension is labelled as (:a, :b, :c) while the other ones simply remain numeric. This would allow X[:,2] to return an LArray{Float64,1,(:a, :b, :c)} instead of a simple array. I mean, for now I can get away with simply using an array of LArray, but if I wanted to do a simple linear transform (like PCA) I would have to do something like  L*hcat( Array{Float64}.(X)...) and I would lose all the labelling. The best alternative would be to do something like  mL(x) -> L*x; mL.(X), but it would be nice to have everything in matrix form.

**Comment by rafaqz** [comment]
You can try it in my fork, although the syntax is old now. I will eventually put in another pull request as I am using this, but I'm pretty busy and the the underlying code changed a lot so it needs a rethink. It's especially difficult to make it generalised to N dimensions.

**Comment by Deduction42** [comment]
Right, you know what? I don't think it will really need to be generalized to N dimensions. The fact is that matrix operations are strictly 2-dimensional and this is the main advantage LabelledArrays has over creating your own structs. Most of the time in anything I do, if an object is a 3D array, it really is nothing more than a bunch of stacked 2D arrays. Anything that I wrote that used this style of coding turned out to be a MATLABism because you needed the object to be a 3D array to do things like taking the mean value of matrices without doing something performance-suicidal like *gasp* doing loops over cell arrays. However, in Julia, you can simply take a mean of a vector of matrices, and it will return the mean matrix without any fuss.

**Comment by ChrisRackauckas** [comment]
Are you sure you aren't looking for an AxisArray from AxisArrays.jl? The purpose of this package is to label the elements, not the slices.

**Comment by Deduction42** [comment]
Right, thanks for letting me know. I looked at it, and while it seems really suitable for a number of other purposes, I am aware of a few tradeoffs. Namely, it is hard to re-attach labels to arrays after doing some transformation math.

I think this package is a better fit for what I'm trying to do (which is build an unscented Kalman filter that allows state transition and observation functions to have labels). This requires applying some mathematical transformations that result in sigma points that need labelling as they are all being evaluated by the function. This essentially borrows old MATLAB code I downloaded and hacked that treats the sigma points as columns in a matrix. 

This package keeps labelling better and if I have to do a transformation on a labelled vector "x" where it is safer to lose the labelling, I can perform the transformation on x[:], and then easily re-apply the labelling on the answer by simply using typeof(x)(y).

**Comment by rafaqz** [comment]
The reason I made this pull request is that AxisArrays indices aren't calculated at compile time (unless something has changed). There's also a lot of complexity in AxisArrays I never need that gets in the way of a pull request, while modifying this package to label the slices was easy.

If this concept can't fit in here I can make a new package that just does multi dimensional labelling at compile time.

**Comment by rafaqz** [comment]
Yes that's an easy way to do this, but not totally satisfactory.

`x[a, b]` syntax is sometimes nicer and probably faster than `x[a][b]`. The matrix can be simpler for doing other things too, if say it needs to be backed with another kind of array, or you want to broadcast on the matrix, use blas, etc.

**Comment by ChrisRackauckas** [comment]
If you have the time to implement the slicing form, go for it. The two standard LArrays shouldn't be touched though, but this other form is complementary, mostly for the linear algebra

**Comment by rafaqz** [comment]
Great. I'll try to use identical syntax just with extra tuples of symbols for each additional axis of labels
