### ISSUE TITLE
syntax preference

### ISSUE THREAD

**Issue by pearsonca** [JuliaDiffEq/LabelledArrays.jl#12]
Per discussion at epirecipes meeting, would ideally be able to use these more like:

```
mutable_u0 = [a=1.0, b=2.0, c=3.0]
static_u0 = @S[a=1.0, b=2.0, c=3.0]
```
i.e., less code noise and more like how named tuples work currently.

Also, seems like the static version should be able to do type inference like the mutable version does?

**Comment by ChrisRackauckas** [comment]
The static version has to define the type in a second step because right now it's built off of FieldVector from StaticArrays.jl. It would be better to directly utilize an interface over named tuples, almost like how a static array is just an interface over tuples. 

We need the macro in both cases in order to define the conversion. I think it can be like:

```julia
mutable_u0 =@LVector [a=1.0, b=2.0, c=3.0]
static_u0 = @SLVector [a=1.0, b=2.0, c=3.0]
```

In theory it could work.

@MSeeker1340 @YingboMa

**Comment by MSeeker1340** [comment]
An alternative choice could be

```julia
mutable_u0 = @LVector [a=>1.0, b=>2.0, c=>3.0]
static_u0 = @SLVector [a=>1.0, b=>2.0, c=>3.0]
```

This mimics the construction of `Dict`s. In fact, maybe drop the macros altogether since when evaluated the argument is just an array of `Pair{Symbol, T}`, i.e.

```julia
mutable_u0 = LArray([:a=>1, :b=>2, :c=>3]) # LArray(AbstractArray{Pair{Symbol,T},N}) where {T,N}
static_u0 = SLArray([:a=>1, :b=>2, :c=>3]) # same story
static_M = SLArray([:a=>1 :c=>3; :b=>2 :d=>4]) # also works for matrices
```

An additional benefit is that keyword arguments are internally represented as `Pair`s, so for one-dimensional arrays we can have convenient factory methods `LVector` and `SLVector` that are keyword-only (I assume Julia's kwargs preserve their ordering?):

```julia
LVector(;kwargs...) = LArray(collect(kwargs))
mutable_u0 = LVector(a=>1, b=>2, c=>3)

# same for SLVector
```

Of course the "named tuple" style could also work, but then we're forced to use macros.

**Comment by ChrisRackauckas** [comment]
Would the pair form infer size for SLArray?

**Comment by MSeeker1340** [comment]
> Would the pair form infer size for SLArray?

Good question... haven't thought about this angle. Maybe a macro is needed after all?

**Comment by ChrisRackauckas** [comment]
The other option is type-piracy on `cat` anyways, but IMO it seems cool to do.

**Comment by MSeeker1340** [comment]
Did some experiments and found that the biggest issue for `LArray([:a=>1, :b=>2])` is that the symbols are not known at compile time, so the factory methods are not type stable (this is confirmed by `@code_warntype`).

On the other hand, using `NamedTuple` as an intermediate conversion object should in theory work since the fields are encoded in the type information. However since `NamedTuple`s are linear in nature we need to specify sizes for anything other than a vector, which is a slight inconvenience. The constructor/constructor macro families are thus:

1. `LArray((2,2), (a=1, b=2, c=3, d=4))` : Basic constructor for LArray (need to specify size)

   1b. `LArray((2,2); a=1, b=2, c=3, d=4)` : Alternative form using kwargs

2. `SLArray{Tuple{2,2}}((a=1, b=2, c=3, d=4))` : Basic constructor for SLArray (need to specify size as type signature)

   2b. `SLArray{Tuple{2,2}}(a=1, b=2, c=3, d=4)` : Alternative form using kwargs

3. `LVector((a=1, b=2))` : Can infer size for vectors

   3b. `LVector(a=1, b=2)` : Alternative form using kwargs

4. `SLVector((a=1, b=2))`  : Ditto

   4b. `SLVector(a=1, b=2)` : Ditto

The disadvantage of this approach is that the macro form `@(S)LArray [a=1 b=2; c=3 d=4]` cannot be written easily using the named tuple constructors. In fact it might be easier to directly use the inner constructors instead. On the other hand the pairs approach is much simpler, for which we can just walk the expression tree and change every occurrence of `a=1` to `:a=>1`, then call the pairs constructor on the transformed expression. But again the type instability issue makes this not feasible.

**Comment by ChrisRackauckas** [comment]
I think 1-4 look great. The macro for inline matrices would be nice but I don't think that's essential if we have this other syntax which IMO is quite nice itself.

**Comment by ChrisRackauckas** [comment]
Completed via https://github.com/JuliaDiffEq/LabelledArrays.jl/pull/35
